---
apiVersion: jetstream.nats.io/v1beta2
kind: Account
metadata:
  name: admin
  namespace: nats
spec:
  name: admin
  servers:
  - nats://nats:4222
  tls:
    secret:
      name: nats-admin-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
